version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1.3
    commands:
      - apt-get update -y
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - apt-get install -y libpq-dev libzip-dev
      - apt-get install -y php-pgsql
      - curl -sS https://getcomposer.org/installer -o composer-setup.php 
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - echo Updating phpenv
      - cd ~/.phpenv && git pull
      - cd ~/.phpenv/plugins/php-build && git pull
      - phpenv install --list
  pre_build:
    commands:
      - phpenv install 8.1.3
      - composer install
      - npm install
  post_build:
    commands:
      - rm -rf /tmp/*
artifacts:
  files:
    - '**/*'
  name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
  upload-artifacts: yes
  logs: yes